<?php
/*
 * TWCMS 1.0
 * Global Configuration File
 *
 * Coded by Steven Bower
 * TurnWheel Designs (cc) 2012
 */

if (!defined('SECURITY')) exit;

$cfg = array(
	/* Script Config */
	// Set to TRUE to enable "Debug" mode
	// This should be disabled for live sites
	'debug' => TRUE,

	/****
	 * Processing Config
	 * Resource settings apply to both CSS and JS files
	 ****/

	/*
	 * If set to TRUE, parents will be checked if page is not found.
	 *
	 * Example: /about/some, if about_some is not found
	 * "about" will be checked before throwing 404 error
	 *
	 * Default FALSE, so parent will not be checked
	 */
	'p_tryParents' => FALSE,

	/*
	 * Load resources for root pages on subpages?
	 *
	 * If FALSE, it will not load parent resources for subpages
	 * Ex: on page /about/history, it will not check for about.js/css
	 *
	 * Default is TRUE, so both about.js & about_history.js will be loaded
	 */
	'res_checkRoot' => TRUE,

	/*
	 * Resource Recursive Check
	 * Default: FALSE
	 *
	 * If TRUE, in case of /about/some/person;
	 * about.js, about_some.js, and about_some_person.js would loaded
	 *
	 * If FALSE, just about.js and about_some_person.js
	 * unless res_checkRoot is FALSE, then just about_some_person.js
	 *
	 * Recommended to keep off unless really needed,
	 * as it can be inefficient for large menu tress.
	 */
	'res_recursive' => FALSE,

	/* Encryption Settings */
	// Algorithm for generating one-way hashes
	// (Default: sha512); see php.net/hash_algos for options
	'hash_algo' => 'sha512',

	// Algorithm for generating two-way enc keys
	// (Default: MCRYPT_3DES); see mcrypt.ciphers for options
	'enc_algo' => 'tripledes',

	// Seed key for enc_algo (NOTE: CHANGE ONLY DURING INITIAL INSTALL)
	'enc_key' => 'CHANGE ME ONCE',

	// Admin Login
	'admin' => array('user' => 'admin','pass' => 'somedude'),

	// Image Upload Settings (if needed)
	'image_types' => array('png','jpg','jpeg'),
	'image_size' => 600, // Size determines length of largest side
	'image_size_th' => 150, // Size of thumbnail

	/*
	 * Module Settings
	 *
	 * mods_avail just passes the names onto
	 * tw_loadmod in lib/security.inc.php
	 * They can be disabled with <mod>_enable => FALSE flag
	 *
	 * For custom mods, just add it to the list with
	 * the proper naming convention.
	 *
	 * <mod>_onload function is called during library init
	 */
	'mods_avail' => array(
		'sql', 'error', 'forms',
		'user', 'mailchimp'
	),

	// Used internally to track which modules have been loaded
	'mods_loaded' => array(),

	/* SQL Settings */
	'sql_enable' => TRUE, // Is DB connection even required?
	// Host name for SQL Database ('localhost' works for most installations)
	'sql_host' => 'localhost',
	// Username for SQL login (Recommend you do NOT use root)
	'sql_user' => 'somewebsite',
	'sql_pass' => 'SQLPass123', // Password for SQL user
	'sql_name' => 'somewebsite', // MySQL Database name

	/* Error Settings */
	'error_enable' => TRUE, // Enable custom error system
	// Display custom php error template?
	// Will load error.php.html. If debug mode is on, it will load
	// error.php.debug.html, which will show full error details.
	// Debug should be disabled on live production sites
	'error_template' => TRUE,
	'error_savedb' => FALSE, // Save error details to DB for record keeping?
	'error_email_enable' => TRUE, // Enable emailing of errors?
	// Error email configurations
	'error_email' => array(
		'date' => 'g:ia T \o\n F j, Y', // Date format for emails
		'to' => array('errors@turnwheel.com'),
		'subject' => '[Error Report]',
		'headers' => 'From: errors@turnwheel.com',
		'body' => 'Error occurred at {date}
-Error Details-
Error: {error_str}
Errno: {error_num} ({error_name})
File: {error_file}
Line: {error_line}

Full report can be viewed at: {url}/errors/{error_sqlid}/

This email was auto-generated by {version}',
	),

	/* Form Settings */
	// Array of form settings (Key is its name)
	'forms' => array(
		'contact' => array(
			// Array of field names to process
			'fields' => array('name', 'email', 'message'),

			// Array of required fields
			'required' => array('name', 'email', 'message'),

			// Save received data to DB?
			// Requires 'sql' module to be enabled
			'savedb' => FALSE,

			// Redirect to page after submission?
			// If FALSE, not redirect happens.
			// If a string, it uses string as destination URL
			'redirect' => '/contact/thankyou',

			// ** Email Configurations **

			// Format of dates in emails
			'email_date' => 'g:ia T \o\n F j, Y',

			// "admin" and "user" are static options
			'emails' => array(
				'admin' => array(
					'enable' => TRUE,

					// Array of emails to send to
					// For admin only. For user is must be a fieldname
					'to' => array('yourname@example.com'),

					// Subject of email
					'subject' => 'Contacted by {name}',

					// Additional email headers (optional)
					// From: and Reply-To: are most common
					// You can enter in {field} to use data here
					// Example: From: {name}<{email}>
					'headers' => 'From: {name}<{email}>',

					// Body of email with {} for var replacements
					// {date} is provided by the library
					// Tabs (\t) are automatically stripped
					'body' => '{name} has contacted you through SomeWebsite.com:

					{message}

					------
					Replies to this email go to {email}
					Message Sent @ {date}
					Automated Email Sent By SomeWebsite.com'
				),
				'user' => array(
					'enable' => FALSE,
					// Field name to grab "to" email from
					'to' => 'email',
					'subject' => 'Thankyou for contacting TWCMS',
					'headers' => 'From: SomeWebsite<contact@somewebsite.com>',
					'body' => 'Thank you for contacting us.

					If your message contained an inquiry, we will try to reply
					to you within 3-4 business days.

					Thank you for your interest in TWCMS

					------
					Message Received @ {date}
					Automated Email Sent By SomeWebsite.com'
				),
			),
		),
	),

	/* User Settings */
	// Enable user login and registration systems
	// requires that sql_enable = TRUE and user table has been created
	'user_enable' => TRUE,
	// Seconds until cookies expire (default 604800, or 1 month)
	'user_expire' => 604800,
	// Enable registration??
	// This allows you to temporarily or permanently
	// disable user registration. Simply blocks access to register page.
	'user_regenable' => TRUE,
	// Notify moderator of new registrations?
	'user_regnotify' => TRUE,
	// Require mod approval on registration?
	// Overrides regnotify setting
	'user_modreg' => TRUE,
	// Send welcome email to new registrations?
	'user_welcome' => FALSE,
	// Email templates and configuration as part of the user system
	// This includes user/mod notifications, and mod approval
	'user_emails' => array(
		// Format of dates in emails
		'date' => 'g:ia T \o\n F j, Y',

		// Email for admin notification
		'regnotify' => array(
			'to' => array('steven@turnwheel.com'),
			'subject' => '[TWCMS] New Registration',
			'headers' => 'From: SomeWebsite<contact@somewebsite.com>',
			'body' => 'A new user has registered an account.

			-User Information-
			{fields}

			More Details: {wwwurl}admin/user/{userid}

			------
			Registration Received @ {date}
			Automated Email Sent By SomeWebsite.com'
		),

		// Email for admin moderation
		'modreg' => array(
			'to' => array('steven@turnwheel.com'),
			'subject' => '[TWCMS] New Member: Approval Required',
			'headers' => 'From: SomeWebsite<contact@somewebsite.com>',
			'body' => 'A new user has requested member access.

			-User Information-
			{fields}

			Visit the admin area below to approve this new user.
			More Details: {wwwurl}admin/user/{userid}

			------
			Registration Received @ {date}
			Automated Email Sent By SomeWebsite.com'
		),

		// Welcome message sent to user
		'welcome' => array(
			'subject' => 'Welcome to TWCMS!',
			'headers' => 'From: SomeWebsite<contact@somewebsite.com>',
			'body' => 'Dear {firstname},

			Welcome to TWCMS, and thank you for joining our website.

			You may now login at to our website by going to:
			{wwwurl}login

			------
			Registration Received @ {date}
			Automated Email Sent By SomeWebsite.com'
		),

		// Account approved
		// only used if modreg is true, this will be sent
		// to the user to notify their account is now active
		// Will only be sent if perm U_NOTIFIED is not set
		'approved' => array(
			'subject' => 'TWCMS Account Approved',
			'headers' => 'Fromt: SomeWebsite<contact@somewebsite.com>',
			'body' => '{firstname} {lastname}-

			Your account for TWCMS has been approved by our moderators.
			You may now login to your account at {wwwurl}login

			Thank you for joining TWCMS.

			------
			Registration Received @ {date}
			Automated Email Sent By SomeWebsite.com'
		),

		// Request to reset password
		'pass_forgot' => array(
			'subject' => '[TWCMS] Request for password reset',
			'headers' => 'From: SomeWebsite<no-reply@somewebsite.com>',
			'body' => 'A request was sent using the Password Recovery Tool
			for this email address. If this request was not sent by you, please
			ignore this email.

			If you are attempting to reset your password, following the link below
			to continue the password reset process.

			{reseturl}

			The above link expires within 24 hours of password reset request.
			If the link has expired, please use our Password Recovery Tool again
			to re-send the request.

			------
			Password Reset Request @ {data}
			Automated Email Sent By SomeWebsite.com'
		),

		// Password has been reset
		'pass_reset' => array(
			'subject' => '[TWCMS] Password reset',
			'headers' => 'From: SomeWebsite<no-reply@somewebsite.com>',
			'body' => 'The password for your TWCMS account has been reset
			using the Password Reset Tool.

			New Password: {password}

			You may now login with the above auto-generated password.
			It is suggested you immeditely change this password once logged in.
			You can change your account profile at: {wwwurl}user/profile

			----
			Password Reset @ {date}
			Automated Email Sent By SomeWebsite.com'
		),
	),

	/* MailChimp Settings */
	'mailchimp_enable' => FALSE, // Enable API

	// Mail Chimp End Points (See Mailchimp Docs For Details)
	'mc_ep' => 'http://us2.api.mailchimp.com/1.3/',
	'mc_key' => '{paste key}', // API Key (account login)
	'mc_listid' => 'effa235ac8', // Unique list id for list to be used
);

/* Define constants */
// Abs. local path to library files
define('LPATH', '/www/SomeWebsite.com/www/lib/');

// PREFIX Note: If changed, you must rename all your CSS and JS files!
// css/<prefix>.<page>.css
// js/<prefix>.<page>.js
define('PREFIX', 'pre'); // Prefix used for cookies, file names, etc.

// Image upload directory (full path)
define('IMGPATH', '/www/SomeWebsite.com/www/uploads/');
define('IMGURL', '/uploads/'); // Image upload URL (relative path)
define('CPATH', 'content/'); // Path to content directory
define('DOMAIN', 'SomeWebsite.com'); // Root domain name of website
define('BASEURL', '/'); // Relative path from root
define('SSLURL', 'https://'.DOMAIN.'/'); // Path to SSL server
define('WWWURL', 'http://'.DOMAIN.'/'); // Path to main website

// Maps settings
define('MAPS_HOST', 'maps.google.com');
// SomeWebsite.com
define('MAPS_KEY', 'ABQIAAAAZReS-Ex4akb7OZJr5kruGxQCvPwXk464zndFkQpy_L80v-esWBSEOIUIQxIGb9olf2owYHTsqjjZGg');
// dev.somewebsite.com
//define('MAPS_KEY', 'ABQIAAAAZReS-Ex4akb7OZJr5kruGxTOYl9STBTHMd_HDDjgXxc08qZ7wBRvNiTUXiXoGUcFgP0pf4mTJPAfcw');

/*
 * Define Bit Flags
 * Do not edit unless you know what you are doing!
 */

/* User Flags (Permissions) */
if ($cfg['user_enable']) {
	define('U_LOGIN', 1); // Basic login privledges
	// Marked if they have been "approved" and notified
	// This is only used if user_modreg is enabled
	define('U_NOTIFIED', 2);
	define('U_EDITOR', 4);
	define('U_ADMIN', 8);

	// Default perms for new accounts
	define('U_DEFAULT', $cfg['user_modreg'] ? 0 : U_LOGIN);

	// Default perms for guests
	define('U_GUEST', 0);
}

/* Other Flags [CUSTOM] */
define('T_APPROVE', 1); // JUST A SAMPLE

/*
 * Do Not Edit Below This Line
 * These values should never change
 */

define('NOW', time());
define('SSL', isset($_SERVER['HTTPS']) && strtolower($_SERVER['HTTPS']) === 'on');

// Full URL is the current full domain path
// Just takes into account SSL
define('FULLURL', SSL ? SSLURL : WWWURL);

// Get requested path
define('REQUESTURL',isset($_SERVER['REQUEST_URI']) ? $_SERVER['REQUEST_URI'] : '/');
define('VERSION', 'TWCMS 1.0-U'); // CMS Version

// Save User's IP Address as constant
define('USERIP', isset($_SERVER['REMOTE_ADDR']) ?
			htmlspecialchars($_SERVER['REMOTE_ADDR'], ENT_QUOTES, 'UTF-8') : 'N/A');

// EOF
