<?php
/*
 * Error Module Config
 */

$cfg = array(
	// Enable module?
	'error_enable' => TRUE,

	// Display custom php error template?
	// Will load error.php.html. If debug mode is on, it will load
	// error.php.debug.html, which will show full error details.
	// Debug should be disabled on live production sites
	'error_template' => TRUE,
	'error_savedb' => FALSE, // Save error details to DB for record keeping?
	'error_email_enable' => TRUE, // Enable emailing of errors?

	// Error email configurations
	'error_email' => array(
		'date' => 'g:ia T \o\n F j, Y', // Date format for emails
		'to' => array('errors@turnwheel.com'),
		'subject' => '[Error Report]',
		'headers' => 'From: errors@turnwheel.com',
		'body' => 'Error occurred at {date}
-Error Details-
Error: {error_str}
Errno: {error_num} ({error_name})
File: {error_file}
Line: {error_line}

Full report can be viewed at: {url}/errors/{error_sqlid}/

This email was auto-generated by {version}',
	)
);

// EOF
